[Mellanox] PSU led platform API fixes
shlomibitton/sonic-buildimage pull request #37
Opened 2020-12-10 15:40 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- Why I did it**
Fix setting PSU led to different states.
Fix return False if unsupported color request.

**- How I did it**
Fix import missing information.
Return 'False' when unsupported led color is requested, preventing an exception.

**- How to verify it**
Try to set PSU LED to different status with Mellanox platform device.
Try to set PSU LED color to unsupported color with Mellanox platform device.

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-12-12 02:41 UTC, keboliu requested changes

2020-12-12 02:41 UTC, keboliu commented on installer/x86_64/install.sh
> +# Check if the CPU vendor is 'Intel' and disable c-states if True
Hmmmmm, guess you didn't have a clean branch...

2020-12-13 09:19 UTC, shlomibitton commented on installer/x86_64/install.sh
> +# Check if the CPU vendor is 'Intel' and disable c-states if True
Fixed.

2020-12-14 01:29 UTC, Junchao-Mellanox requested changes

2020-12-14 01:29 UTC, Junchao-Mellanox commented on platform/mellanox/mlnx-platform-api/sonic_platform/led.py
> +        Led.STATUS_LED_COLOR_OFF: 1,
I remember we don't support LED OFF. Could you confirm that with a test? You can also check it with Vadim.

2020-12-14 01:29 UTC, Junchao-Mellanox commented on platform/mellanox/mlnx-platform-api/sonic_platform/led.py
> +                return False
We can return False here, but the color of ComponentFaultyIndicator will still be an invalid color, maybe we need also handle that?

2020-12-14 13:51 UTC, shlomibitton commented on platform/mellanox/mlnx-platform-api/sonic_platform/led.py
> +                return False
Yes it is not supported, I removed it.

2020-12-15 07:58 UTC, Junchao-Mellanox approved these changes

2020-12-15 18:07 UTC, closed without merging