Stop teamd docker to shutdown all LAGS on 'config reload'
shlomibitton/sonic-buildimage pull request #39
Opened 2021-01-28 11:16 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- What I did**
'teamd' service will stop before all other services.
This is to stop all LAG's before restarting syncd service when running 'config reload' command.

**- How I did it**
Change the order of dependent services of SWSS.

**- How to verify it**
Run 'config reload' command.

**- Previous command output (if the output of a command-line utility has changed)**
The operation failed when a large number of PortChannel configured on the system.
Unloading the LAG's on the driver take a lot of time.
This will make the driver unload all netdev fast and the operation will execute properly

**- New command output (if the output of a command-line utility has changed)**
Success.

2021-01-28 11:31 UTC, nazariig requested changes

2021-01-28 11:31 UTC, nazariig commented on files/scripts/swss.sh
>          for dep in ${DEPENDENT}; do
@shlomibitton please move this in front of `PEER`

2021-01-28 11:33 UTC, shlomibitton commented on files/scripts/swss.sh
>          for dep in ${DEPENDENT}; do
please check now

2021-01-28 12:33 UTC, nazariig approved these changes

2021-01-28 13:08 UTC, liat-grozovik commented on files/scripts/swss.sh
> +        for dep in ${DEPENDENT}; do
please document what is the logic of this change and what is it about to fix

2021-01-28 13:08 UTC, liat-grozovik commented on files/scripts/swss.sh
> +        for dep in ${DEPENDENT}; do
what is multi instance depended and it is now before any of them unlike it was before. should it?

2021-01-28 13:11 UTC, liat-grozovik commented
please check this fix without any patch for the teamd start flow.
we want to be sure the system is working with large number of port channels. enclose is my suggestion:
- configure system with large number of port channels (80 at least), set ip to each
- save configuration
- reload config 
- restart swss 
- reload system with reboot command (do it few times)
- reload system with fastboot command (do it few times)
- reload system with warmboot command (do it few times)

all port channel should be configured and ips are set. all DBs are synced.

2021-01-31 14:30 UTC, shlomibitton commented on files/scripts/swss.sh
> +        for dep in ${DEPENDENT}; do
I changed the PR description can you please check now?
**DEPENDENT="radv dhcp_relay"
MULTI_INST_DEPENDENT="teamd"**
these are lists of services, I am not sure why we have two seperate groups, but all dependent services of SWSS should stop before.

2021-01-31 14:30 UTC, shlomibitton commented
> please check this fix without any patch for the teamd start flow.
> we want to be sure the system is working with large number of port channels. enclose is my suggestion:
> 
> * configure system with large number of port channels (80 at least), set ip to each
> * save configuration
> * reload config
> * restart swss
> * reload system with reboot command (do it few times)
> * reload system with fastboot command (do it few times)
> * reload system with warmboot command (do it few times)
> 
> all port channel should be configured and ips are set. all DBs are synced.

Tested all the above and it is working as expected

2021-01-31 14:42 UTC, liat-grozovik commented
Thanks
Approved ;-)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: shlomibitton <notifications@github.com>
Sent: Sunday, January 31, 2021 4:30:59 PM
To: shlomibitton/sonic-buildimage <sonic-buildimage@noreply.github.com>
Cc: Liat Grozovik <liatg@nvidia.com>; Comment <comment@noreply.github.com>
Subject: Re: [shlomibitton/sonic-buildimage] Change the order of stopping dependent services of SWSS (#39)


please check this fix without any patch for the teamd start flow.
we want to be sure the system is working with large number of port channels. enclose is my suggestion:

  *   configure system with large number of port channels (80 at least), set ip to each
  *   save configuration
  *   reload config
  *   restart swss
  *   reload system with reboot command (do it few times)
  *   reload system with fastboot command (do it few times)
  *   reload system with warmboot command (do it few times)

all port channel should be configured and ips are set. all DBs are synced.

Tested all the above and it is working as expected

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/shlomibitton/sonic-buildimage/pull/39#issuecomment-770391146>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKTABAYOZ4TEDBQPKYVKBGDS4VSSHANCNFSM4WW4AVTQ>.

2021-02-02 10:30 UTC, liat-grozovik approved these changes

2021-02-10 20:09 UTC, closed without merging