[DHCP] Add DHCP relay support for IPv6
shlomibitton/sonic-buildimage pull request #49
Opened 2021-03-30 14:38 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

#### Why I did it
Currently the DHCP docker created 'isc-dhcrelay' instances only for IPv4 networks.
The package support IPv6 also, this PR will add the option to configure IPv6 relay agents in SONiC.
In addition, enhancement for DHCPv6 monitor application implementation.

#### How I did it
Edit supervisord template to create new agents when IPv6 DHCP relays are configured, according to the package instructions.
Edit the 'dhcmon' code base to monitor DHCMPv6 along with DHCPv4.

#### How to verify it
Configure a DHCPv6 relay on a VLAN interface (downstream network) and provide a DHCP server (upstream network)
like described on the feature HLD which can be found here:
https://github.com/shlomibitton/SONiC/blob/shlomi_dhcpv6/doc/DHCPv6_Relay/DHCPv6_Relay_HLD.md

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-05-05 10:33 UTC, nazariig requested changes

2021-05-05 18:36 UTC, nazariig requested changes

2021-05-05 18:36 UTC, nazariig commented on src/dhcpmon/src/dhcp_device.c
> +static dhcpv4_message_type_t v4_monitored_msgs[] = {
@shlomibitton why we have `dhcpv4_message_type_t` but the values are for `DHCPv6`?

2021-05-06 13:34 UTC, nazariig requested changes

2021-05-06 13:34 UTC, nazariig commented on src/dhcpmon/src/dhcp_device.c
> +                (((struct sockaddr_in6*)(ifa_tmp->ifa_addr))->sin6_addr.__in6_u.__u6_addr16[0] != 0x80fe)) {
@shlomibitton can we avoid magic numbers?

2021-05-06 13:34 UTC, nazariig commented on src/dhcpmon/src/dhcp_device.h
> -    uint64_t counters[DHCP_COUNTERS_COUNT][DHCP_DIR_COUNT][DHCP_MESSAGE_TYPE_COUNT];
@shlomibitton how about making it a struct and putting v4/v6 counters in a single place?

2021-05-06 13:34 UTC, nazariig commented on src/dhcpmon/src/dhcp_devman.c
> +}
@shlomibitton missing a newline?

2021-05-10 13:51 UTC, shlomibitton commented on .gitmodules
> +	url = https://github.com/shlomibitton/sonic-utilities
It is not a typo, needed it to build an image with the new CLI I added.
It is not part of the PR, but was required to build it from Jenkins build image task.
It will be removed on external PR.

2021-05-10 13:51 UTC, shlomibitton commented on src/sonic-yang-models/tests/test_sonic_yang_models.py
> +    pyang_tree_cmd = "pyang -Vf tree -p /usr/local/share/yang/modules/ietf ./yang-models/*.yang > ./yang-models/sonic_yang_tree"
We don't, it is a WA to build the image, it was a known issue.
This will be removed on external PR.

2021-05-10 13:53 UTC, shlomibitton commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +{% set _dummy_v4 = ipv4_num_relays.update({'count': ipv4_num_relays.count + 1}) %}
Fixed.

2021-05-10 14:48 UTC, shlomibitton commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +{% if VLAN and vlan_name in VLAN and 'dhcpv6_servers' in VLAN[vlan_name] and VLAN[vlan_name]['dhcpv6_servers']|length > 0 %}
I agree, but same as here, this is the way it was done previously for IPv4 relay, you think we should refactor the code?

2021-05-10 14:48 UTC, shlomibitton commented on src/dhcpmon/src/dhcp_device.c
> +static dhcpv4_message_type_t v4_monitored_msgs[] = {
It is a mistake, fixed

2021-05-10 14:53 UTC, shlomibitton commented on src/dhcpmon/src/dhcp_device.c
> +        bool is_ipv4 = *(u_int16_t *)(&(context->buffer[ETHER_TYPE_OFFSET])) == IPV4_EtherType;
Fixed :)

2021-05-10 14:57 UTC, shlomibitton commented on src/dhcpmon/src/dhcp_device.c
> +                (((struct sockaddr_in6*)(ifa_tmp->ifa_addr))->sin6_addr.__in6_u.__u6_addr16[0] != 0x80fe)) {
Fixed

2021-05-10 15:28 UTC, shlomibitton commented on src/dhcpmon/src/dhcp_device.h
> -    uint64_t counters[DHCP_COUNTERS_COUNT][DHCP_DIR_COUNT][DHCP_MESSAGE_TYPE_COUNT];
Fixed

2021-05-10 15:29 UTC, shlomibitton commented on src/dhcpmon/src/dhcp_devman.c
> +}
Fixed

2021-05-10 15:29 UTC, shlomibitton commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +{% endif %}
Fixed

2021-05-11 12:31 UTC, nazariig commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +command=/usr/sbin/dhcrelay -d -6 --name-alias-map-file /tmp/port-name-alias-map.txt -l {{ vlan_name }}
@shlomibitton i saw `Loopback` in IPv4 configuration for DHCP, that's why i asked.

2021-05-11 12:33 UTC, nazariig commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +{% if VLAN and vlan_name in VLAN and 'dhcpv6_servers' in VLAN[vlan_name] and VLAN[vlan_name]['dhcpv6_servers']|length > 0 %}
@shlomibitton would be better to refactor but this can be done in separate PR

2021-05-11 14:44 UTC, shlomibitton commented on src/sonic-config-engine/tests/sample_output/py2/docker-dhcp-relay.supervisord.conf
> +command=/usr/sbin/dhcpmon -id Vlan1000 -iu Vlan2000 -iu PortChannel02 -iu PortChannel03 -iu PortChannel04 -iu PortChannel01 -im eth0 -4
I have added DHCPv6 to minigraph and improved the test, please review

2021-05-11 14:45 UTC, shlomibitton commented on src/sonic-config-engine/tests/sample_output/py3/docker-dhcp-relay.supervisord.conf
> +command=/usr/sbin/dhcpmon -id Vlan1000 -iu Vlan2000 -iu PortChannel01 -iu PortChannel02 -iu PortChannel03 -iu PortChannel04 -im eth0 -4
I have added DHCPv6 to minigraph and improved the test, please review

2021-05-12 09:55 UTC, nazariig commented on dockers/docker-dhcp-relay/docker-dhcp-relay.supervisord.conf.j2
> +command=/usr/sbin/dhcrelay -d -6 --name-alias-map-file /tmp/port-name-alias-map.txt -l {{ vlan_name }}
@shlomibitton ok. Then no issues.

2021-05-12 09:57 UTC, nazariig approved these changes

2021-06-01 09:45 UTC, closed without merging