[hostcfgd] Enhance hostcfgd to check feature state and run less system calls
shlomibitton/sonic-buildimage pull request #56
Opened 2021-06-22 14:01 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

#### Why I did it
Currently hostcfgd is implemented in a way each feature which is enabled/disabled triggering execution of systemctl enable/unmask commands which eventually trigger 'systemctl daemon-reload' command.
Each call like this cost 0.6s and overall add a overhead of ~12 seconds of CPU time.
This change will verify the desired state of a feature and the current state of this feature on systemd and triggere a system call only when must.

#### How I did it
Check each feature status on systemd before executing a system call to enable and reload the systemctl daemon.

#### How to verify it
Build an image with this change and observe less system calls are executed.

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

#### Description for the changelog

#### A picture of a cute animal (not mandatory but encouraged)

2021-06-22 17:23 UTC, liat-grozovik commented
@shlomibitton  please check the existing unit test for hostcfg and see how you can extend it. it will be requested.

2021-06-22 17:23 UTC, stepanblyschak commented on src/sonic-host-services/scripts/hostcfgd
> +            cmd = "sudo systemctl status {}.{} | grep Loaded".format(feature_name, feature_suffixes[-1])
How much CPU time calling "systemctl status" costs?

2021-06-23 06:57 UTC, shlomibitton commented on src/sonic-host-services/scripts/hostcfgd
> +            cmd = "sudo systemctl status {}.{} | grep Loaded".format(feature_name, feature_suffixes[-1])
real	0m0.019s
user	0m0.008s
sys	0m0.004s

2021-06-23 10:33 UTC, shlomibitton commented
> @shlomibitton please check the existing unit test for hostcfg and see how you can extend it. it will be requested.

@liat-grozovik I added another UT to verify the new approach.

2021-06-23 10:37 UTC, liat-grozovik requested changes

2021-06-23 10:37 UTC, liat-grozovik commented on src/sonic-host-services/scripts/hostcfgd
> +            #Check if it is already disabled, if yes skip the system call
can you please have space after comment starts with #? i see this is used is most of the cases so better to align

2021-06-23 10:37 UTC, liat-grozovik commented on src/sonic-host-services/tests/hostcfgd/test_vectors.py
> +        "DualTorCaseWithNoSystemCalls",
I probably dont understand the logic of the UT and it has no comments.
can you please explain what are you trying to test and how this is achieved?

2021-06-23 10:47 UTC, shlomibitton commented on src/sonic-host-services/tests/hostcfgd/test_vectors.py
> +        "DualTorCaseWithNoSystemCalls",
On the new test case I initialized the 'mocked_subprocess' Popen function to return 'enabled' on stdout as the new code request it:
https://github.com/shlomibitton/sonic-buildimage/pull/56/files#diff-27d10088e7a11c3ae41f16e5272d96926179ae179c61d6fc32a25d0cfa40907eR745

This is simulating a real switch where all features are enabled by 'systemd' and the 'Feature' table.
On this scenario we would like to skip all system calls because all are already enabled by systemd and this is what configured to be on Feature table.
at the end of this case here:
https://github.com/shlomibitton/sonic-buildimage/pull/56/files#diff-f5d8f3e52583dba5fc292bc7da61c2fe173464b4a7136b1e168c2c69b7b760d1R83

We verify if system calls were triggered during the test, on this case we expect to have non.
So we verify it using this as an empty list:
https://github.com/shlomibitton/sonic-buildimage/pull/56/files#diff-12a04feb8021d605272ba7897b65852877a4059670b5d8c350543cc7f6fc53cdR367

2021-06-23 10:53 UTC, shlomibitton commented on src/sonic-host-services/scripts/hostcfgd
> +            #Check if it is already disabled, if yes skip the system call
Fixed.

2021-06-23 11:41 UTC, stepanblyschak commented on src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
> +            if test_name == "DualTorCaseWithNoSystemCalls":
Just curious why DualTorCase?

2021-06-23 11:41 UTC, stepanblyschak commented on src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
> +                attrs = {'communicate.return_value': ('enabled', 'error')}
This is needs to be part of test_vectors

2021-06-23 12:00 UTC, shlomibitton commented on src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
> +            if test_name == "DualTorCaseWithNoSystemCalls":
It is random, no special reason for it.
It is just to verify this functionality is working so I took one of them.

2021-06-23 12:00 UTC, shlomibitton commented on src/sonic-host-services/tests/hostcfgd/hostcfgd_test.py
> +                attrs = {'communicate.return_value': ('enabled', 'error')}
Can you check now?

2021-06-23 12:09 UTC, stepanblyschak approved these changes

2021-06-27 11:19 UTC, closed without merging